import { db } from "@/index";
import * as schema from "@/db/schemas";
import fs from "fs";
import path from "path";
import { users, USERS_SEED_FILE } from "./01-users";

const IDS_PATH = path.resolve("src/db/seeds/.auth-user-ids.json");

export default async function seed() {
  console.log("🌱 Starting database seed...");

  // 1. Roles
  console.log("Seeding Roles...");
  const [rolePrincipal, roleClassTeacher, roleTeacher, roleParent] = await db
    .insert(schema.roles)
    .values([
      { name: "principal", description: "School Administrator" },
      { name: "class_teacher", description: "Class/Form Teacher" },
      { name: "teacher", description: "Subject Teacher" },
      { name: "parent", description: "Student Guardian/Parent" },
    ])
    .returning();

  // 2. School
  console.log("Seeding School...");
  const [school] = await db
    .insert(schema.schools)
    .values({
      name: "Mwangaza Junior Secondary",
      code: "MJS-001",
    })
    .returning();

  // 3. Academic Year (e.g., 2026 Kenyan School Calendar)
  console.log("Seeding Academic Year...");
  const [academicYear] = await db
    .insert(schema.academicYears)
    .values({
      schoolId: school.id,
      name: "2026",
      startDate: "2026-01-05",
      endDate: "2026-10-30",
    })
    .returning();

  // 4. Terms
  console.log("Seeding Terms...");
  const [term1, term2, term3] = await db
    .insert(schema.terms)
    .values([
      {
        academicYearId: academicYear.id,
        termNumber: 1,
        startDate: "2026-01-05",
        endDate: "2026-04-10",
      },
      {
        academicYearId: academicYear.id,
        termNumber: 2,
        startDate: "2026-05-04",
        endDate: "2026-08-07",
      },
      {
        academicYearId: academicYear.id,
        termNumber: 3,
        startDate: "2026-08-31",
        endDate: "2026-10-30",
      },
    ])
    .returning();

  // 5. Grades (Junior Secondary: 7, 8, 9)
  console.log("Seeding Grades...");
  const [grade7, grade8, grade9] = await db
    .insert(schema.grades)
    .values([
      { schoolId: school.id, name: "Grade 7", level: 7 },
      { schoolId: school.id, name: "Grade 8", level: 8 },
      { schoolId: school.id, name: "Grade 9", level: 9 },
    ])
    .returning();

  // 6. Streams
  console.log("Seeding Streams...");
  const [stream7East, stream7West] = await db
    .insert(schema.streams)
    .values([
      { gradeId: grade7.id, name: "East" },
      { gradeId: grade7.id, name: "West" },
    ])
    .returning();

  // 7. Learning Areas (CBC Curriculum)
  console.log("Seeding Learning Areas...");
  const [math, english, science] = await db
    .insert(schema.learningAreas)
    .values([
      { schoolId: school.id, name: "Mathematics", code: "MAT", isActive: true },
      { schoolId: school.id, name: "English", code: "ENG", isActive: true },
      {
        schoolId: school.id,
        name: "Integrated Science",
        code: "ISC",
        isActive: true,
      },
    ])
    .returning();

  // 8. Grading Scales (CBC Standard)
  console.log("Seeding Grading Scales...");
  await db.insert(schema.gradingScales).values([
    {
      schoolId: school.id,
      name: "CBC Grading",
      minScore: "80.00",
      maxScore: "100.00",
      grade: "EE",
      remark: "Exceeding Expectation",
    },
    {
      schoolId: school.id,
      name: "CBC Grading",
      minScore: "60.00",
      maxScore: "79.99",
      grade: "ME",
      remark: "Meeting Expectation",
    },
    {
      schoolId: school.id,
      name: "CBC Grading",
      minScore: "40.00",
      maxScore: "59.99",
      grade: "AE",
      remark: "Approaching Expectation",
    },
    {
      schoolId: school.id,
      name: "CBC Grading",
      minScore: "0.00",
      maxScore: "39.99",
      grade: "BE",
      remark: "Below Expectation",
    },
  ]);

  // 9. Profiles & User Roles
  console.log("Seeding Profiles...");

  // Read the IDs generated by create-users.ts.
  const idsPath = path.resolve(USERS_SEED_FILE);

  if (!fs.existsSync(idsPath)) {
    throw new Error(
      `User IDs file not found at ${idsPath}. Run the user seeder first.`,
    );
  }

  const userIds: Record<string, string> = JSON.parse(
    fs.readFileSync(idsPath, "utf-8"),
  );

  // Ensure every configured user has a corresponding Supabase Auth ID.
  for (const user of users) {
    if (!userIds[user.role]) {
      throw new Error(
        `Missing Supabase Auth ID for role "${user.role}". Run the user seeder first.`,
      );
    }
  }

  // Generate profile data from the user configuration.
  const profileValues = users.map((user) => ({
    id: userIds[user.role],
    fullName: user.fullName,
    phone: user.phone,
  }));

  const profiles = await db
    .insert(schema.profiles)
    .values(profileValues)
    .returning();

  // Keep individual profile variables accessible to the rest of the seeder.
  const principal = profiles.find(
    (profile) => profile.id === userIds.principal,
  );

  const teacher = profiles.find((profile) => profile.id === userIds.teacher);

  const parent = profiles.find((profile) => profile.id === userIds.parent);

  // Fail early if any expected profile is missing.
  if (!principal || !teacher || !parent) {
    throw new Error(
      "Failed to retrieve the principal, teacher, or parent profile.",
    );
  }

  // Role assignments remain explicitly connected to the appropriate roles.
  await db.insert(schema.userRoles).values([
    {
      userId: principal.id,
      roleId: rolePrincipal.id,
      schoolId: school.id,
    },
    {
      userId: teacher.id,
      roleId: roleTeacher.id,
      schoolId: school.id,
    },
    {
      userId: parent.id,
      roleId: roleParent.id,
      schoolId: school.id,
    },
  ]);

  // 10. Teacher Assignments
  console.log("Seeding Teacher Assignments...");
  await db.insert(schema.classTeacherAssignments).values({
    teacherId: teacher.id,
    streamId: stream7East.id,
    academicYearId: academicYear.id,
  });

  await db.insert(schema.subjectTeacherAssignments).values({
    teacherId: teacher.id,
    streamId: stream7East.id,
    learningAreaId: math.id,
    academicYearId: academicYear.id,
  });

  // 11. Students
  console.log("Seeding Students...");
  const [student1, student2] = await db
    .insert(schema.students)
    .values([
      {
        schoolId: school.id,
        admissionNumber: "ADM-2026-001",
        fullName: "Ian Kamau",
        status: "active",
      },
      {
        schoolId: school.id,
        admissionNumber: "ADM-2026-002",
        fullName: "Joy Akinyi",
        status: "active",
      },
    ])
    .returning();

  // 12. Student Enrollments
  console.log("Seeding Enrollments...");
  await db.insert(schema.studentEnrollments).values([
    {
      studentId: student1.id,
      streamId: stream7East.id,
      academicYearId: academicYear.id,
      startDate: "2026-01-05",
    },
    {
      studentId: student2.id,
      streamId: stream7East.id,
      academicYearId: academicYear.id,
      startDate: "2026-01-05",
    },
  ]);

  // 13. Parent-Student Link
  console.log("Seeding Parent-Student records...");
  await db.insert(schema.parentStudents).values({
    parentId: parent.id,
    studentId: student1.id,
    verificationStatus: "verified",
    verifiedAt: new Date(),
    verifiedBy: principal.id,
  });

  // 14. Assessments
  console.log("Seeding Assessments...");
  const [assessment] = await db
    .insert(schema.assessments)
    .values({
      schoolId: school.id,
      academicYearId: academicYear.id,
      termId: term1.id,
      learningAreaId: math.id,
      name: "Term 1 Mid-Term Mathematics",
      assessmentType: "School Based Assessment",
      maxScore: "100.00",
      status: "published",
      createdBy: teacher.id,
    })
    .returning();

  // 15. Student Results
  console.log("Seeding Results...");
  await db.insert(schema.studentResults).values([
    {
      assessmentId: assessment.id,
      studentId: student1.id,
      score: "85.50",
      grade: "EE",
      remark: "Excellent work, keep it up",
      enteredBy: teacher.id,
    },
    {
      assessmentId: assessment.id,
      studentId: student2.id,
      score: "72.00",
      grade: "ME",
      remark: "Good understanding of concepts",
      enteredBy: teacher.id,
    },
  ]);

  console.log("✅ Seeding completed successfully!");
}
